- name: Create wg config file
  ansible.builtin.template:
    src: client_interface.j2
    dest: "/etc/wireguard/{{ interface_name }}.conf"

- name: Start wg interface with config file
  ansible.builtin.command: "wg-quick up {{ interface_name }}"
  ignore_errors: true
  become: yes
