- name: Create wg config file
  ansible.builtin.template:
    src: client_interface.j2
    dest: "/etc/wireguard/{{ interface_name }}.conf"

- name: Start wg interface with config file
  ansible.builtin.command: "wg-quick up {{ interface_name }}"
  ignore_errors: true
  register: wg_interface_state
  become: yes

- name: Restart wg interface if already running
  ansible.builtin.shell: "wg-quick down {{ interface_name }}; wg-quick up {{ interface_name }}"
  when: wg_interface_state.rc == 1
  become: yes
