---
- name: Include OS-specific tasks
  include_tasks: "{{ os_item.value }}"
  when: ansible_os_family == os_item.key
  loop:
    - { key: "Rocky", value: "setup-rocky.yml" }
    - { key: "Debian", value: "setup-debian.yml" }
  loop_control:
    loop_var: os_item

- name: Generate public-private keypair
  ansible.builtin.shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/privatekey
  become: yes

- name: Save privatekey in usable var
  ansible.builtin.shell: cat /etc/wireguard/privatekey
  register: wg_private_key
  become: yes

- name: Save publickey in usable var
  ansible.builtin.shell: cat /etc/wireguard/publickey
  register: wg_public_key
  become: yes

- name: Load specific configuration task
  include_tasks: "{{ config_type.value }}"
  when: wg_type == config_type.key
  loop:
    - { key: "client", value: "client_config.yml" }
    - { key: "server", value: "server_config.yml" }
  loop_control:
    loop_var: config_type
